### ISSUE TITLE
Integrate Tika Parser to Parse Function for extracting Text and metadata 

### ISSUE THREAD

**Issue by thammegowda** [USCDataScience/sparkler#10]
The current parse function is limited to outlinks

**Comment by thammegowda** [comment]
Resolved! Using Apache Tika's Autodetect parser [ParseFunction.scala](https://github.com/USCDataScience/sparkler/blob/ed4999a9df012e1426139835fe0829e001445609/sparkler-app/src/main/scala/edu/usc/irds/sparkler/pipeline/ParseFunction.scala)

**Comment by thammegowda** [comment]
TODO: Parse should also produce few metadata fields and plain text content along with links.

**Comment by MuhammadTalhaAfzal** [comment]
Did anybody started to implement plugin for plain text content and title indexing in solr?

**Comment by karanjeets** [comment]
@MuhammadTalhaAfzal,

I am yet to start this and will probably do over the weekend. Please let me know if you are looking to collaborate.
