### ISSUE TITLE
[MEMEX] Introduce REST API for Sparkler

### ISSUE THREAD

**Issue by sujen1412** [USCDataScience/sparkler#103]
Having a REST api to Sparkler would be a great addition. 
If someone has already started working on this then lets collaborate or else I will start initial documentation and share links to that here soon.

**Comment by chrismattmann** [comment]
👍

**Comment by thammegowda** [comment]
@sujen1412 Nobody is working on REST API, you are good to start documentation and share the links.

**Comment by sujen1412** [comment]
Starting documentation at - docs.sparklerapi.apiary.io
