### ISSUE TITLE
Update CONTRIBUTING.md to include commit comments instructions

### ISSUE THREAD

**Issue by sujen1412** [USCDataScience/sparkler#108]
It might be a good idea to have contributors have their commits start with Fix ISSUE=# for easier tracking of the commits. And having the issue number in the comment would also mean that github would automatically link that commit to the respective issue enabling faster review/merging. 

I currently dont see anything like that on the CONTRIBUTING.md. 

Thoughts  ?

**Comment by thammegowda** [comment]
Thanks @sujen1412 You are right. I will fix it
