### ISSUE TITLE
Define plugin dir as a cmd line flag

### ISSUE THREAD

**Issue by buggtb** [USCDataScience/sparkler#114]
#### Issue Description
The plugin dir is effectively hard coded into the jar in the yaml config. It needs to be defineable because otherwise you're stuck with whatever directory your CI tool or whatever built from.

#### How to reproduce it
Just look in the yaml file.

#### Environment and Version Information
All envs.

#### Contributing
I'll fix this.

**Comment by thammegowda** [comment]
Done. Here is how to do : `-Dpf4j.pluginsDir=$DIR` in CLI

See https://github.com/USCDataScience/sparkler/blob/master/bin/sparkler.sh for an example
