### ISSUE TITLE
Create a sparkler "distribution"

### ISSUE THREAD

**Issue by buggtb** [USCDataScience/sparkler#120]
We need to create a distribution that containers:

- Sparkler jar
- Solr Schema
- External configuration lookup
- Plugins as a folder structure
- Matching Banana dashboard?

**Comment by buggtb** [comment]
i've pushed some stuff that picks up the app, conf and stuff and builds a few archives. Should work for testing.

**Comment by thammegowda** [comment]
@buggtb aren't you supposed to raise a pull request and then merge it yourself?

You are the boss you can do the way you like! It's just a suggestion
