### ISSUE TITLE
base package "usc.edu.ir" instead of "usc.edu.irds"

### ISSUE THREAD

**Issue by smadha** [USCDataScience/sparkler#14]
Should we make our base package "usc.edu.ir" to maintain consistency with our previous projects and jars already pushed to maven central?

**Comment by thammegowda** [comment]
as you know the groups' home page is http://irds.usc.edu, the package name shall reflect its domain name in reverse.

**Comment by thammegowda** [comment]
if this project gets accepted to Apache Incubation (hopefully), the current package name will not matter!

**Comment by smadha** [comment]
Well OK. IRDS always made sense but my only point was consistency with
previous projects in maven central. If it wont matter later, let it be what
it is.

--
Madhav Sharan

**Comment by thammegowda** [comment]
My question is - There will be many more projects to come under this
groupid, is it a good idea to carry over a typo of first project to all the
upcoming projects?
I don't think so :-)

I got your point. May be the older project be updated with newer groupId?
This usually happens whenever a project moves to a new home.

~~
TG
sent from my phone.

**Comment by smadha** [comment]
Well it was never a typo. We created directory before we named irds, and it still makes some sense. Honestly I like edu.usc.irds more but also edu.usc.ir is more colloborative. 

Updating older projects is even harder, there is much to do updating package in TIKA documentation etc..
