### ISSUE TITLE
CLI argument to focus the crawl to a specific domain

### ISSUE THREAD

**Issue by voltek62** [USCDataScience/sparkler#140]
#### New feature

Currently, in order to crawl specific domain, I need to edit regex file for every crawl.

My suggestion is to add CLI argument to focus the crawl to a specific domain.

e. g for crawling only specific domains in seed files
--specificdomain=TRUE 

Your project is amazing, I prepare a R package to deploy Sparkler on Openstack with one code line and get results easily with R language.

All the best

**Comment by thammegowda** [comment]
Thanks for creating this issue and providing all the details.
Looks like a nice addition to the project. We will work on it.

**Comment by chrismattmann** [comment]
Thanks so much!

**Comment by ravituduru** [comment]
May I know to edit this regex file for specific domain.
