### ISSUE TITLE
Read large files using Tika

### ISSUE THREAD

**Issue by voltek62** [USCDataScience/sparkler#149]
Tika is stopping the extraction at 100KB limit. 
We might loose some content in larger web pages and documents. 

Can you increase the limit ?

----------
WARN  ParseFunction$:75 [Executor task launch worker-0] - Your document contained more than 100000 characters, and so your requested limit has been reached. To receive the full text of the document, increase your limit. (Text up to the limit is however available).

org.apache.tika.sax.WriteOutContentHandler$WriteLimitReachedException: Your document contained more than 100000 characters, and so your requested limit has been reached. To receive the full text of the document, increase your limit.

**Comment by thammegowda** [comment]
@voltek62  Thanks for describing the issue.  I recently Increased to 100MB. Closing this
