### ISSUE TITLE
Sparkler wiki - links and downloads

### ISSUE THREAD

**Issue by srinidhinandakumar** [USCDataScience/sparkler#155]
#### Issue Description

I faced issues with finding the links to solr 6.4.0 but found them in the archive [here](https://archive.apache.org/dist/lucene/solr/6.4.0/) .
The internal directory paths of the extracted content were different - so I modified them on the Sparkler wiki page.
However, now I just downloaded the solr-6.4.0 tar file from wrangler and extracted it to find that the previously mentioned relative file paths (in the commands) were correct.
Can someone please look into the URLs - and the relative paths. 
I might have made a mistake by updating the paths in the commands.
@chrismattmann @thammegowda @sujen1412

**Comment by thammegowda** [comment]
https://github.com/USCDataScience/sparkler/wiki/sparkler-0.1/_compare/7d83a03%5E...7d83a03

Please revert back these edits.

Wondering what went wrong?
You have downloaded source code instead of compiled solr.

**Comment by thammegowda** [comment]
@srinidhinandakumar  Thanks
