### ISSUE TITLE
Removing sparkler-app-0.2.0-SNAPSHOT.jar

### ISSUE THREAD

**Issue by misterpilou** [USCDataScience/sparkler#159]
First i've got an issue with the sparkler-app-0.2.0-SNAPSHOT.jar so i deleted it, then i couldn't rebuild the project, Is there any particular reason to keep the sparkler-app-0.2.0-SNAPSHOT.jar.
Well fyi, removing the:
```
<dependency>
    <groupId>edu.usc.irds.sparkler</groupId>
    <artifactId>sparkler-api</artifactId>
    <version>0.2.0-SNAPSHOT</version>
</dependency>
```
from sparkler-app/pom.xml fix the issue, I'll do it myself if you confirm that it is not useful anymore & when i'll finish my work

**Comment by misterpilou** [comment]
Is there an utility with the sparkler-app/resources/log4j.properties file?

**Comment by thammegowda** [comment]
Mr. Pilou @misterpilou 

- the build works fine, I have tested it. 
- unless you know what you are doing with mxven, please do not edit pom.xml (not to remove sparkler-api dependency )
- Looks like there is some setup issue in your environment.
- make a fresh clone of this repository and and run `mvn clean package`
- If maven reports failure, paste the maven build log to https://paste.apache.org/ and share the  link here.

**Comment by thammegowda** [comment]
oh do you mean `sparkler-app/src/main/resources/log4j.properties`?
That one is set to DEBUG, see `log4j.logger.edu.usc.irds=DEBUG`, meant for using during development time logs (my IntelliJ IDEA picks up this during development)

Then the one in `conf` directory,  has `log4j.logger.edu.usc.irds=INFO`. It is meant for the final production deployment, and thus goes into final package.

**Comment by misterpilou** [comment]
Yes i mean that, okay i got it

**Comment by thammegowda** [comment]
I am interested in hearing if these log4j.properties files caused any trouble

**Comment by misterpilou** [comment]
No it didn't made any, i tried to use sparkler-app/src/main/resources dir before knowing that it was actually the resources dir was the conf one

**Comment by thammegowda** [comment]
I hope this is resolved.  If not please reopen it
