### ISSUE TITLE
Standalone Docker image

### ISSUE THREAD

**Issue by buggtb** [USCDataScience/sparkler#166]
For a scalable deployment you don't need solr etc in the docker image, a standalone one will be useful.

**Comment by x0rzkov** [comment]
Is there any updates on the dockerization of sparkler ? would be awesome to try it quickly.

**Comment by thammegowda** [comment]
@x0rzkov Please see https://hub.docker.com/r/uscdatascience/sparkler/tags?page=1&ordering=last_updated
