### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by chaitra-rs** [USCDataScience/sparkler#176]
Is it possible to run sparkler without docker?
I already have a python set up, I want to integrate sparkler

**Comment by thammegowda** [comment]
Yes. it's possible (we have done that before creating docker image) but requires more effort. 

* Setup Solr: https://github.com/USCDataScience/sparkler/wiki/sparkler-0.1
* Build Sparkler: run `mvn package -DskipTests` at the root of this project dir. 

See this dockerfile
https://github.com/USCDataScience/sparkler/blob/5c2201310623b70e6bf024e51e521eb4bffc4723/sparkler-deployment/docker/Dockerfile#L38-L55
