### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by chrome83** [USCDataScience/sparkler#177]
Hello dev, sorry for my newbie question, but i need to add sparkler user to sudo, or just if it's possible the root password for docker container to install software via apt.

**Comment by thammegowda** [comment]
you dont need to add sparkler user to root.
You should install docker and have it running. 
Please refer to this page https://github.com/USCDataScience/sparkler/wiki/Build-and-Deploy#using-prebuilt-docker-image

**Comment by chrome83** [comment]
Ok, sorry for my bad english, my fault. :smile: 
I try to explain better, in the docker sparkler container, i need to add some software via apt.
The command need elevated privilege.
If it's possible having root password?

**Comment by thammegowda** [comment]
@chrome83 
this is a question related to `docker` and you can find documentation everywhere on how to get root user inside a  docker image.
 
By default we have added non sudo user `sparkler`
https://github.com/USCDataScience/sparkler/blob/5c2201310623b70e6bf024e51e521eb4bffc4723/bin/dockler.sh#L36

Try changing that user to `root` and see if it works (I have not tested it recently;). 
Here is a  link to docker documentation https://docs.docker.com/engine/reference/commandline/exec/

**Comment by chrome83** [comment]
@thammegowda 
many thank's, it worked, sorry for my stupid question :smile: , but i think when you have builded the images, have inserted your root password.
Best regard :hand:
