### ISSUE TITLE
silly question

### ISSUE THREAD

**Issue by vwoloszyn** [USCDataScience/sparkler#187]
Hi Guys, 

It's everything working fine.. However, I cannot find the HTML content stored on SOLR... what would be the best way to access the HTML content of the crawled webpages? 

All the best,
Vinicius

**Comment by ravituduru** [comment]
you can  find fields in solr as raw_text and extracted text where statua:Fetched.I think this is what you are looking.

**Comment by vwoloszyn** [comment]
Hi  @ravituduru thank you very much. However, it only provides "extracted_text", which is raw text, instead of HTML... Is there a way to enable the extraction of HTML as well? Thank you in advance...
