### ISSUE TITLE
Make storage engine pluggable

### ISSUE THREAD

**Issue by buggtb** [USCDataScience/sparkler#196]
Should support both Solr and Elastic OOTB, but also thinking about JSON support in Postgres etc for other folk.

**Comment by lewismc** [comment]
Hi @buggtb OK I only just saw this. We are of course currently working on the StorageProxy and StorageClient implementations. 
It reminded me of all of the work I've done on [Apache Gora](http://gora.apache.org) over the years but I thought it might be a bit too much overkill at this time. 
What are your thoughts on Gora? Have you used it?

**Comment by lewismc** [comment]
Superseded by https://github.com/USCDataScience/sparkler/issues/218
