### ISSUE TITLE
Define interfaces for the plugins

### ISSUE THREAD

**Issue by thammegowda** [USCDataScience/sparkler#20]
- [X] URL Filter
- [X] Fetcher
- [ ] Parser
- [X] URL Normalizer
- [ ] Extractor
- [ ] Generator

PS
this is incomplete list

**Comment by thammegowda** [comment]
Status Update : 

We have defined `URLFilter` and `URLNormalizer`.

The remaining will be done once we started integrating Nutch's plugins using plugin frawework

**Comment by sujen1412** [comment]
@thammegowda, where can I find the code for the completed issues, maybe I could use that as example before starting development of new plugin ? Is there a commit linked to the issue number ?

**Comment by thammegowda** [comment]
We dont have a proper documentation at the moment (Adding to my todo list to work on it, thanks for reporting).

Meanwhile: here is how I added a new plugin: https://github.com/USCDataScience/sparkler/pull/100
If you need to define a plugin, the interfaces+baseclasses here could be examples: https://github.com/USCDataScience/sparkler/tree/master/sparkler-api/src/main/java/edu/usc/irds/sparkler


TODO: update the wiki with proper docs.

**Comment by micheladennis** [comment]
Quick Quesiton,
What is the parser extension point?

**Comment by thammegowda** [comment]
@micheladennis  Sorry, there was no extension point added to Parser at the moment.
This video might help to add a new plugin https://www.youtube.com/watch?v=Ib8OwmoRj-Q
