### ISSUE TITLE
Visual Analytics : Create admin dashboard to crawldb to visualize the stats in realtime

### ISSUE THREAD

**Issue by thammegowda** [USCDataScience/sparkler#23]
Get stats from solr crawldb by querying it  and visualize the results using charts like D3js (or similar)

**Comment by jorgelbg** [comment]
Perhaps there is no need of building something from scratch, since the stats are stored on Solr, we could use something like https://github.com/lucidworks/banana (port of Kibana) so adding an exported version of the panel could be enough, plus every body can customize it.

**Comment by thammegowda** [comment]
👍  @jorgelbg Thanks. 
+1 for Banana.

**Comment by karanjeets** [comment]
@jorgelbg: Thanks for the suggestion. Banana is definitely a good visual aid.

However, apart from visuals, we are also looking forward to some interaction with the Crawler through a user interface. This can provide many benefits, for eg: guiding the crawl.

**Comment by manishdwibedy** [comment]
Hi, I would love to pitch in. If anyone can help me what exactly needs to be done.. Thanks.

**Comment by karanjeets** [comment]
Hi @manishdwibedy 
Thanks for joining in. There are two user interfaces we are targeting here:
-  Banana Dashboard connected to CrawlDB (Solr).
-  An interactive user interface (preferably in angularJS) which can start, monitor and visualize the crawl.

I would recommend you starting the banana dashboard and add graphs which can help visualize the crawl data. Start by running Sparkler on your local system and analyzing the Solr schema.

**Comment by karanjeets** [comment]
@manishdwibedy 
Thanks for your time today. Since you have Sparkler working on your local machine now, I am really looking forward to the first draft of Banana dashboard.

Once again, thanks for your interest in Sparkler!

**Comment by manishdwibedy** [comment]
@karanjeets Check the PR #38  for the banana dashboard.

**Comment by karanjeets** [comment]
Thanks @manishdwibedy!! 👍 

I will review and merge. For the next steps, please create sub-tasks (as GitHub issues) for Banana dashboard, so that others can also contribute in this.  :)

**Comment by thammegowda** [comment]
Resolved by #39
