### ISSUE TITLE
Job hangs for a minute when Kafka is not configured

### ISSUE THREAD

**Issue by thammegowda** [USCDataScience/sparkler#33]
When Kafka server is not configured or active, the crawl job make repeated attempts to establish connection which adds reasonable amount of delay.

By default, Kafka feature shall be disabled in configuration.

@karanjeets Thoughts? Can you have a look this?

**Comment by karanjeets** [comment]
@thammegowda Yes, this is what I was talking about earlier. It's on my list.

@rahulpalamuttam Do you want to work on this?  :)

**Comment by rahulpalamuttam** [comment]
@karanjeets @thammegowda 
You beat me to it.
Yes I would love to work on this.
Give me some time I will submit a PR.

Do you want to have kafka disabled by default and have users enable it by uncommenting?

**Comment by karanjeets** [comment]
That's great, @rahulpalamuttam  :)

Yes, we want to disable Kafka by default. Let's keep another configuration parameter such as `kafka.enabled` instead of commenting/uncommenting. What do you think?

**Comment by rahulpalamuttam** [comment]
That sounds good to me.

The change would be simple:

1. Adding the appropriate annotated variable to read in `kafka.enabled`

2. Have a conditional block around the following line of code https://github.com/USCDataScience/sparkler/blob/master/sparkler-app/src/main/scala/edu/usc/irds/sparkler/pipeline/Crawler.scala#L124

**Comment by karanjeets** [comment]
Cool 👍

**Comment by karanjeets** [comment]
Thanks, @rahulpalamuttam  :)
This is now resolved.
