### ISSUE TITLE
Dockerize Sparkler

### ISSUE THREAD

**Issue by karanjeets** [USCDataScience/sparkler#40]
Dockerize Sparkler for "Pick and Crawl" framework. 

@thammegowda : As discussed, please work on this.

**Comment by thammegowda** [comment]
Update : 
Docker is a good option when we need single machine. Suits for local mode.

For the cluster / distributed mode, docker becomes over kill. 
The better option is ubuntu juju charms https://jujucharms.com/

Investigating Juju Charms

**Comment by petevg** [comment]
If you want to go the charm route, I, and the rest of the Big Data team at Canonical, are happy to help out. You can find me on freenode#juju as petevg. Feel free to ask questions there, or call me out on any PRs in this repo.

**Comment by thammegowda** [comment]
We have a docker for local testing #52,  so closing this issue

However, we are also working on JujuCharms for cloud deployment #50
