### ISSUE TITLE
[MEMEX] Feature to add cookies from configured files to the request header sent by fetcher

### ISSUE THREAD

**Issue by thammegowda** [USCDataScience/sparkler#46]

**Comment by smadha** [comment]
Great Issue. Here is my proposal -
1. Create a seperate schema to store cookies. Schema should have id as hostname
2. Storing cookies should be an additional functionality which can be turned off through configuration
3. Create utility script/app for users to add cookies to schema. These cookies should never be overridden/updated during crawl

Thoughts? 
+ @sujen1412

**Comment by thammegowda** [comment]
@smadha 

Sounds like a great plan. 
Agreed, we will need a storage to preserve cookies.
We need  storage to keep robots.txt and thus resolve - #45 

We need to have a discussion with all of us in team ( @karanjeets @sujen1412 ) before we jump in.

Also please have a look at #45, you may see that they are kind of similar and thus the solution can be designed with a broader scope

**Comment by sujen1412** [comment]
@smadha we should flesh out the details a little more here. 
1. How will a user provide the cookies ? 
2. How will Sparkler store the cookies ? 
3. What is the mechanism to let sparkler know on what hosts to use this cookies ? 
4. How will Sparkler know that the cookie has expired/ or a new cookie is set by the server ? In this case should the crawling stop ? Should sparkler update the cookie in solr ? How will the user know about this ?

**Comment by smadha** [comment]
All these are great points. 
1. How will a user provide the cookies ?
M.S. - My thought is take a input file from user and process it with sparkler. Do you know about any preexisting format? If not we can define one which has a map of host name to cookie value. Will be great if you can share your own file.

How will Sparkler store the cookies?
M.S. My proposal is to store in a solr schema. We should define a concrete schema before we implement, but my idea was to maintain one solr doc for each domain/subdomain name.
.
  What is the mechanism to let sparkler know on what domains to use the cookies ?
M.S. If cookie processing is enabled we will search in our schema for available cookies for that domain/subdomain


How will Sparkler know that the cookie has expired/ or a new cookie is set by the server ? In this case should the crawling stop ? Should sparkler update the cookie in solr ? How will the user know about this ?

Great point. My proposal is to mimic browser behaviour for cookies. We should put this check while searching for cookies in solr. 
We can put cookie info in debug logs. In my opinion we should not stop crawl. 
We can add more logs for cookies manually added by user. 

Will be great if you can demo your current approach to us.

Thanks
