### ISSUE TITLE
[MEMEX] Change Enum config to have unfetched in place of new

### ISSUE THREAD

**Issue by sujen1412** [USCDataScience/sparkler#49]
To maintain the Nutch lingo and crawler lingo of a url that is unfetched, I suggest replacing the enumconfig to have UNFETCHED in place of the value NEW.

**Comment by karanjeets** [comment]
@sujen1412 This is a good suggestion. I don't mind changing the enumconfig to UNFETCHED. 

@thammegowda What do you think?

**Comment by thammegowda** [comment]
:+1: from my side.

**Comment by thammegowda** [comment]
Resolved in #69
