### ISSUE TITLE
Exclude org.json:json library since its license is incompatible with Apache License 2.0

### ISSUE THREAD

**Issue by buggtb** [USCDataScience/sparkler#54]
FYI if you are still going to incubate sparkler,  you'll need to remove the org.json parser because of an incompatible license.

**Comment by thammegowda** [comment]
Thanks Tom.. I will replace the org.json library with a compatible library https://wiki.debian.org/qa.debian.org/jsonevil

**Comment by thammegowda** [comment]
`org.json` is brought by `tika-parsers`, we have to change it there.
This issue stands still until I/somebody resolves https://issues.apache.org/jira/browse/TIKA-1804
