### ISSUE TITLE
URL filter regex

### ISSUE THREAD

**Issue by MyraBaba** [USCDataScience/sparkler#55]
Hi,

Am I missing the url filter ?  How I can tell the sparkler app to url filter  rules ?

in general  or per domain

thx

**Comment by thammegowda** [comment]
The rules file is `conf/regex-urlfilter.txt` [1].
The file itself has some documentation about the format. In addition, the underlying plugin is same as the one in Nutch. So, the nutch documentation is also useful [2].
Please ensure that plugin configuration is as per [3].

The rules are general, they are applied to all URLs. Let me know if this was helpful or you face any trouble

[1] https://github.com/USCDataScience/sparkler/blob/master/conf/regex-urlfilter.txt
[2] https://wiki.apache.org/nutch/NutchTutorial#A.28Optional.29_Configure_Regular_Expression_Filters
[3] https://github.com/USCDataScience/sparkler/blob/master/conf/sparkler-default.yaml#L74

**Comment by karanjeets** [comment]
@MyraBaba Were you able to set the url filter rules? Do you have any further question on this?

**Comment by thammegowda** [comment]
Closing this issue due to no response from issue creator.

Feel free to reopen this issue if you face it again.
