### ISSUE TITLE
Working with remote spark.

### ISSUE THREAD

**Issue by buggtb** [USCDataScience/sparkler#56]
Has anyone tried this with a non local spark?

I ask because when I try and run on a remote spark I get class mismatch errors:

java.lang.RuntimeException: java.io.InvalidClassException: org.apache.spark.rpc.netty.RequestMessage; local class incompatible: stream classdesc serialVersionUID = -5447855329526097695, local class serialVersionUID = -2221986757032131007

But then when I check the versions, you guys use Spark 1.6.1 which requires Scala 2.10.x, but you use Scala 2.11.x and if you try and downgrade to 2.10 it doesn't compile.

**Comment by thammegowda** [comment]
Thanks for reporting. 

This usually happens due to version mismatch. As you know, we have to match the library version with the version of the spark cluster. 

@karanjeets has tried it on distributed mode, @karanjeets please comment on this.

> But then when I check the versions, you guys use Spark 1.6.1 which requires Scala 2.10.x, but you use Scala 2.11.x and if you try and downgrade to 2.10 it doesn't compile

I believe spark 1.6.1 can run with both the versions of scala - 2.10 and 2.11. However, scala 2.11 is default.
We are using spark 1.6.1 with scala 2.11.
https://github.com/USCDataScience/sparkler/blob/4a0ead6f448ce0bf6fd6f7666998714c293e9462/pom.xml#L33-L35

```
        <spark.version>1.6.1</spark.version>
        <scala.version>2.11</scala.version>
        <scala.library.version>${scala.version}.8</scala.library.version>
```

I tried downgrading to scala 2.10
```
        <spark.version>1.6.1</spark.version>
        <scala.version>2.10</scala.version>
        <scala.library.version>${scala.version}.6</scala.library.version>
```

However, scala `2.10` is pretty old that it cant be built on JDK 8, we need to switch to JDK 7
http://stackoverflow.com/questions/24197836/

Let me know if this helped or if you have suggestions.

**Comment by buggtb** [comment]
thanks for that. I saw the jar for spark on scala 2.11 but can find a spark
distro for scala 2.11 do you guys just compile it?

Tom

**Comment by arelaxend** [comment]
Yes! And it works ! You have to match versions and also to use addJar()

**Comment by karanjeets** [comment]
@buggtb Yes, I compiled Spark 1.6.1 with Scala 2.11. Here is the documentation [0]. It works.

[0]: https://spark.apache.org/docs/1.6.0/building-spark.html#building-for-scala-211

**Comment by buggtb** [comment]
fair enough makes sense now. I'll work on updating the spark charm to
support it

**Comment by buggtb** [comment]
Cool, I have a working spark charm for Sparkler now and a working solr cham, so we have all the bits we need for a scalable solution

**Comment by buggtb** [comment]
Okay, spark novice in terms of writing apps over the top of it. If I wanted to run the:

java -jar sparkler-app-0.1-SNAPSHOT.jar crawl -id sjob-1482840394215 -m spark://10.222.81.63:7077 -cdb http://10.222.81.136:8983/solr/crawldb -i 1

Type command, is there currently a way of injecting the jar into the spark classpath. ie how does addJar() work in your world @arelaxend 

Thanks

Tom

**Comment by arelaxend** [comment]
Hi, i am novice too. But I figured out. Easy, you just have to add:
```
    if (sparkMaster.contains("spark")) {
      sc.addJar("file:///PATH_TO_SPARKLER/sparkler/sparkler-app/target/uber-sparkler-app-0.1-SNAPSHOT.jar")
    }
```
After `sc = new SparkContext(conf)` in Crawler.scala file.
Plus, It is not mandatory but I add in the pom.xml file in the maven-shade section:
`<finalName>uber-${project.artifactId}-${project.version}</finalName>`

AS

**Comment by buggtb** [comment]
Ah you did the same as me pretty much :) Cool, I'm not crazy then. https://github.com/USCDataScience/sparkler/pull/60 this should make it a bit cleaner for new users

**Comment by arelaxend** [comment]
Yes, just saw it. The fact is that I personally use local[*] to specify local behavior. And spark:// uri to specify cluster behavior.

**Comment by buggtb** [comment]
Yeah I wrote it to be completely automatic the first time, but then I figured everyone has different requirements and at some point the magic will trip over itself or my auto path detection stuff would stop working for some reason etc, so kept it simple. Happy to make it automatic if @karanjeets or someone wanted it to be.
