### ISSUE TITLE
Felix Plugins : Option to enable and disable easily

### ISSUE THREAD

**Issue by thammegowda** [USCDataScience/sparkler#70]
## Currently, we have: 
 - Maven builds any plugin that is configured to build and places the jars to bundles directory
 - Felix registers any plugin that is under the bundles directory

## What we need:
 - Some way of explicitly telling Felix to ignore some plugins in bundles directory

## Future Work
The next version would be to make maven ignore the plugins that are not used. But it is not needed as of now.

**Comment by thammegowda** [comment]
@karanjeets Have you thought about this, or done any preliminary work on this? I remember we discussed few months ago related to this issue

**Comment by karanjeets** [comment]
Thanks for bringing this up. Yes, we can achieve this through Sparkler's configuration file.
- Adding another parameter `plugins.active` and specify names of the active plugins
- Adding `enable` parameter to each plugin with value true or false 

What do you think?

**Comment by thammegowda** [comment]
I feel `plugins.active` would be convenient.  

Otherwise in option 2, we will have to put `enabled=false` for all other plugins which users are least bothered.  

+1 priority for this issue, we need to disable jbrowser this way since it is dead slow
