### ISSUE TITLE
Felix Version issue

### ISSUE THREAD

**Issue by thammegowda** [USCDataScience/sparkler#76]
Currently, we have multiple versions of felix and osgi in classpath.
[pom.xml](https://github.com/USCDataScience/sparkler/blob/master/pom.xml)
```
        <felix.framework.version>2.0.4</felix.framework.version>
        <felix.core.version>1.4.0</felix.core.version>
        <felix.main.version>5.4.0</felix.main.version>
```

## ToDo:
- Clean this mess - make it easy to upgrade
- set it to the latest stable version

### Notes: 
- `org.osgi` has the specification and `org.apache.felix.*` package has the implementation
- Double check class names for imports, variable declarations and initialization 

### p.s. : 
Caught issues while trying to fix #70

**Comment by karanjeets** [comment]
Yes, let's bring felix framework and main to `5.6.1` (the latest stable version). 

But, as I see the [maven central](https://mvnrepository.com/artifact/org.apache.felix/org.osgi.core/1.4.0), `osgi` is already on the latest stable version `1.4`. Did I miss something?

**Comment by thammegowda** [comment]
Checkout my changes on #77 

> osgi is already on the latest stable version 1.4. Did I miss something?

yes you had to use the groupId `org.osgi` for the OSGI specifications instead of felix.
My PR uses version `6.0.0`
