### ISSUE TITLE
No Terms displayed in Banana

### ISSUE THREAD

**Issue by rainergeissendoerfer** [USCDataScience/sparkler#86]
Using the current Dockerfile deployment there are no terms listed in banana widget. Any idea on who to turn those term analytics on?

**Comment by thammegowda** [comment]
Hi @rainergeissendoerfer ,
Thanks for trying Sparkler and reporting this issue. We are happy to help.
But I will need little more information to understand your situation.
1.  Could you share a screen shot of your dashboard? 

 Maybe these will show some pointers to analyze/fix issue:

2. Did you load the dashboard config from `sparkler-ui/dashboard/Sparkler-Dashboard-Basic`in this repo?  You can load it once and save it in your browser local storage. Let me know if you need more detailed instructions/help on this.
3. If you have loaded the dashboard config in previous step, then the possible issue would be not having any terms in your index. How many fetched resources do yo u have in index? You may check it from http://localhost:8984/solr/crawldb/query?q=status:FETCHED (or wherever your solr is hosted).

**Comment by thammegowda** [comment]
Closing this issue due to no response from issue creator.

Feel free to reopen this issue if you face it again.
