### ISSUE TITLE
Create guidelines and templates for issues and PRs using github templates

### ISSUE THREAD

**Issue by thammegowda** [USCDataScience/sparkler#94]
Github supports templates to bootstrap Issues and Pull request descriptions with necessary details.

TODO:
+ setup `.github/ISSUE_TEMPLATE.md` - this should provide basic skeleton for describing issue. 
+ setup  `.github/PULL_REQUEST_TEMPLATE.md` this should describe succintly . Add checkmarks to include testcases, code conventions check and etc
+ setup `.github/CONTRIBUTING.md` - copy style guides to this file and describe the guidelines.

References for additional details:
+ https://github.com/blog/2111-issue-and-pull-request-templates 
+ https://help.github.com/articles/helping-people-contribute-to-your-project/

Thanks @buggtb for bringing this into our sight and educating us :-)

**Comment by smadha** [comment]
Awesome @thammegowda . This will be very helpful.

I found OpenNLP templates very useful - https://github.com/apache/opennlp/tree/master/.github

**Comment by thammegowda** [comment]
Thanks @smadha, we shall use those templates.
