### ISSUE TITLE
Attach Sparkler to Travis

### ISSUE THREAD

**Issue by buggtb** [USCDataScience/sparkler#97]
If someone gives me project admin rights, I would be happy to hook up Sparkler to Travis so that stuff like:
https://github.com/USCDataScience/sparkler/pull/82 builds failing, are no longer a surprise :)

**Comment by thammegowda** [comment]
@buggtb Please do. You have been given Admin rights :-)

**Comment by thammegowda** [comment]
Should this be closed now? I see you have configured.
