### ISSUE TITLE
Add buggtb to dockerhub collaborators

### ISSUE THREAD

**Issue by buggtb** [USCDataScience/sparkler#99]
Hi guys

I've got juju setup for a nightly charm build on its development channel, like we discussed I'd like to do the same for dockerhub, can someone add buggtb as a collaborator so I can push nightly builds?

**Comment by thammegowda** [comment]
Done.
You should be having admin privileges for this repo in dockerhub
Please check and https://hub.docker.com/r/uscdatascience/sparkler/

Please update this.

**Comment by thammegowda** [comment]
Done
